export const popularServicesList = [
  {
    id: 1,
    title: '크몽어워즈 대상 수상ㅣ대표가 포트폴리오 퀄리티로 제작',
    rating: 4.9,
    reviewCount: 4375,
    price: 50000,
    expertName: '그리미아트디자인',
    src: ['/webp/1-1.webp', '/webp/1-2.webp', '/webp/1-3.webp', '/webp/1-4.webp'],
    link: '/gig/1',
    master: true,
    award: true,
  },
  {
    id: 2,
    title: 'ㅣ대기업협력사ㅣ로고ㅣ명함ㅣ네이밍ㅣ슬로건ㅣ로고디자인',
    rating: 4.9,
    reviewCount: 1064,
    price: 60000,
    expertName: '보울디자인',
    src: ['/webp/2-1.webp', '/webp/2-2.webp', '/webp/2-3.webp', '/webp/2-4.webp'],
    link: '/gig/2',
    master: true,
  },
  {
    id: 3,
    title: '홍대출신ㅣ경력15년 로고업체ㅣ대기업협력사ㅣ맞춤로고전문',
    rating: 4.9,
    reviewCount: 2661,
    price: 60000,
    expertName: '로고마스터',
    src: ['/webp/3-1.webp', '/webp/3-2.webp', '/webp/3-3.webp', '/webp/3-4.webp'],
    link: '/gig/3',
    master: true,
  },
  {
    id: 4,
    title: '로고 랭키 1위 크몽어워즈 KS 11년 연속 1위 수상',
    rating: 4.9,
    reviewCount: 2883,
    price: 150000,
    expertName: '지구컴즈',
    src: ['/webp/4-1.webp', '/webp/4-2.webp', '/webp/4-3.webp'],
    link: '/gig/4',
    prime: true,
    master: true,

    award: true,
  },
  {
    id: 5,
    title: '당일로고 제작ㅣ매출이 상승하는 로고 로고제작 로고디자인',
    rating: 4.9,
    reviewCount: 1534,
    price: 50000,
    expertName: '정튜디오',
    src: ['/webp/5-1.webp', '/webp/5-2.webp', '/webp/5-3.webp'],
    link: '/gig/5',
    master: true,
  },
  {
    id: 6,
    title: '당일작업가능ㅣ명함인쇄ㅣ컬러리스트ㅣ디자인전공ㅣ전문회사인증',
    rating: 4.9,
    reviewCount: 4674,
    price: 50000,
    expertName: '로고한잔',
    src: ['/webp/6-1.webp', '/webp/6-2.webp', '/webp/6-3.webp', '/webp/6-4.webp'],
    link: '/gig/6',
    master: true,
  },
  {
    id: 7,
    title: '크몽어워즈 2년 연속 대상ㅣ전문 디자인 에이전시',
    rating: 4.9,
    reviewCount: 3873,
    price: 80000,
    expertName: 'DAcompany',
    src: ['/webp/7-1.webp', '/webp/7-2.webp', '/webp/7-3.webp', '/webp/7-4.webp'],
    link: '/gig/7',
    prime: true,
    master: true,
  },
  {
    id: 8,
    title: '크몽공식 Prime 로고업체｜로고제작｜로고디자인',
    rating: 4.9,
    reviewCount: 1723,
    price: 90000,
    expertName: '로고이션',
    src: ['/webp/8-1.webp', '/webp/8-2.webp', '/webp/8-3.webp', '/webp/8-4.webp'],
    link: '/gig/8',
    master: true,
  },
  {
    id: 9,
    title: '크몽어워즈 수상ㅣ대한민국 디자인 대상ㅣ초격차 로고디자인',
    rating: 4.9,
    reviewCount: 3470,
    price: 55000,
    expertName: '원스팟디자인',
    src: ['/webp/9-1.webp', '/webp/9-2.webp', '/webp/9-3.webp', '/webp/9-4.webp'],
    link: '/gig/9',
    master: true,
  },
  {
    id: 10,
    title: '감각적인 로고제작, 로고디자인, CI, BI, 브랜딩',
    rating: 4.9,
    reviewCount: 263,
    price: 29000,
    expertName: '디자인메테오',
    src: ['/webp/10-1.webp', '/webp/10-2.webp', '/webp/10-3.webp', '/webp/10-4.webp'],
    link: '/gig/10',
    master: true,
  },
  {
    id: 11,
    title: 'ㅣ심플대장ㅣ 대기업이 인정한 김로고 로고제작',
    rating: 4.9,
    reviewCount: 2252,
    price: 50000,
    expertName: '김로고',
    src: ['/webp/11-1.webp', '/webp/11-2.webp', '/webp/11-3.webp', '/webp/11-4.webp'],
    link: '/gig/11',
    master: true,
  },
  {
    id: 12,
    title: '고급감성로고 쇼핑몰 브랜드 뷰티 심플 로고 디자인 제작',
    rating: 4.9,
    reviewCount: 442,
    price: 98000,
    expertName: 'NVE',
    src: ['/webp/12-1.webp', '/webp/12-2.webp', '/webp/12-3.webp', '/webp/12-4.webp'],
    link: '/gig/12',
    master: true,
  },
  {
    id: 13,
    title: 'ㅣ당일제작ㅣ로고 로고제작 로고디자인, CI BI, 명함',
    rating: 4.9,
    reviewCount: 751,
    price: 120000,
    expertName: '상현디자인연구소',
    src: ['/webp/13-1.webp', '/webp/13-2.webp', '/webp/13-3.webp', '/webp/13-4.webp'],
    link: '/gig/13',
  },
  {
    id: 14,
    title: '24시간 쉽고 빠른 고퀄리티 로고 제작 디자인 전문회사',
    rating: 4.9,
    reviewCount: 1856,
    price: 70000,
    expertName: '모노디자인',
    src: ['/webp/14-1.webp', '/webp/14-2.webp', '/webp/14-3.webp', '/webp/14-4.webp'],
    link: '/gig/14',
  },
  {
    id: 15,
    title: '선착순 단 3명 / 단순 로고가 아닌 작품을 만듭니다.',
    rating: 4.9,
    reviewCount: 240,
    price: 29000,
    expertName: '디자인바오',
    src: ['/webp/15-1.webp', '/webp/15-2.webp', '/webp/15-3.webp', '/webp/15-4.webp'],
    link: '/gig/15',
  },
]
